### ISSUE TITLE
v2.1 Automation Whitespace Bug

### ISSUE THREAD

**Issue by andrewmcodes** [bridgetownrb/bridgetown-cloudinary#5]
>  It appears that it doesn't actually break anything so this is low prio. 😄

## Bug

When running the automation:

```sh
bin/bridgetown apply https://github.com/bridgetownrb/bridgetown-cloudinary
```

On a new Bridgetown v1.2.0.beta3 site, the following output is produced:

```rb
  init :"bridgetown-cloudinary"do
    cloud_name "andrewmcodes"
  end
```

instead of:

```rb
  init :"bridgetown-cloudinary" do
    cloud_name "andrewmcodes"
  end
```

Notice there is no space between the `"`" and `do` in the first example.

## Reproduction Steps

1. Run `bin/bridgetown apply https://github.com/bridgetownrb/bridgetown-cloudinary` in the root of your Bridgetown site
2. Look at output in `config/initializers.rb`

## Desired Solution

Ideally there would be a space between the end of the `"` and `do` here. I tried messing with it for a few minutes and couldn't get it so wanted to get an issue opened for visibility.

## Versions

- Bridgetown `1.2.0.beta3`
- bridgetown-cloudinary `2.1.0`

**Comment by jaredcwhite** [comment]
Yeah, that was an annoying thing I think I fixed on main but it didn't get into the beta3 release. Thanks for tracking it here so we can verify it later.
